export default function ReportTemplate({ companyName, title, columns = [], data = [], generatedDate }) {
  const displayDate = generatedDate || new Date().toLocaleDateString();
  return (
    <div className="bg-white p-8 text-gray-900">
      <div className="relative mb-6 overflow-hidden rounded-t-lg border border-gray-200">
        <div className="h-16 bg-gradient-to-r from-emerald-400 via-green-500 to-violet-500" />
        <div className="relative px-6 pb-6 pt-4 text-center">
          <h1 className="text-3xl font-bold">{companyName}</h1>
          <p className="mt-1 text-sm font-medium text-gray-600">{title}</p>
          <p className="absolute right-6 top-6 text-sm text-gray-600">Generated: {displayDate}</p>
        </div>
      </div>

      <table className="w-full border border-gray-300 text-sm">
        <thead className="bg-slate-100">
          <tr>
            <th className="border border-gray-300 px-3 py-2 text-left font-semibold">Sr No</th>
            {columns.map((column) => (
              <th
                key={column.key}
                className={`border border-gray-300 px-3 py-2 font-semibold ${column.align === "right" ? "text-right" : "text-left"}`}
              >
                {column.header}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {data.length === 0 ? (
            <tr>
              <td colSpan={columns.length + 1} className="border border-gray-300 px-3 py-6 text-center text-gray-500">
                No records available for this report.
              </td>
            </tr>
          ) : (
            data.map((row, index) => {
              return (
                <tr key={`row-${index}`} className="even:bg-gray-50">
                  <td className="border border-gray-300 px-3 py-2">{index + 1}</td>
                  {columns.map((column) => (
                    <td
                      key={`${column.key}-${index}`}
                      className={`border border-gray-300 px-3 py-2 ${column.align === "right" ? "text-right" : "text-left"}`}
                    >
                      {row[column.key] ?? "-"}
                    </td>
                  ))}
                </tr>
              );
            })
          )}
        </tbody>
      </table>

      <div className="mt-6 flex items-center justify-between text-sm text-gray-600">
        <p>{companyName}</p>
        <p>Generated by Eyercall Inventory System</p>
      </div>
    </div>
  );
}
