export function printRecord({ title, fields, timestamp = true }) {
  const el = document.getElementById("print-area");
  if (!el) return;

  const rows = fields
    .filter((f) => f.value != null && f.value !== "")
    .map((f) => `<tr><td style="font-weight:600;width:40%">${f.label}</td><td>${f.value}</td></tr>`)
    .join("");

  el.innerHTML = `
    <div class="print-header">
      <div>
        <h2>${title}</h2>
        <div class="print-sub">EyerFlow Inventory System</div>
      </div>
      ${timestamp ? `<div class="print-sub">${new Date().toLocaleString()}</div>` : ""}
    </div>
    <table>${rows}</table>
    <div class="print-footer">Generated by EyerFlow — ${new Date().toLocaleString()}</div>
  `;

  window.print();
}
